export const INDUSTRY_ICONS = {
  "Agriculture": "🌾",
  "Animal Feed": "🐄",
  "Automobile": "🚘",
  "Automobile Parts": "⚙️",
  "Automation": "🤖",
  "Aviation": "✈️",
  "Bakery": "🥐",
  "Beauty & Cosmetics": "💄",
  "Building Materials": "🧱",
  "Catering": "🍲",
  "Chemicals": "🧪",
  "Cold Storage": "❄️",
  "Computer Hardware": "🖥️",
  "Construction": "🏗️",
  "Consulting": "💼",
  "Courier Services": "📬",
  "Dairy": "🥛",
  "Defense": "🛡️",
  "Digital Marketing": "📱",
  "Distribution": "🚚",
  "E-commerce": "🛒",
  "Education": "🎓",
  "Electrical": "⚡",
  "Electronics": "💻",
  "Energy": "🔋",
  "Engineering": "📐",
  "Event Management": "🎉",
  "Export": "🚢",
  "Fabrication": "🛠️",
  "Fashion": "👗",
  "FMCG": "🛍️",
  "Food Processing": "🥫",
  "Food & Beverages": "🍽️",
  "Furniture": "🪑",
  "Garments": "👕",
  "Gas": "⛽",
  "Gems & Jewellery": "💎",
  "Government Supplier": "🏛️",
  "Graphic Design": "🎨",
  "Handicrafts": "🏺",
  "Handloom": "🧶",
  "Healthcare": "⚕️",
  "Home Decor": "🖼️",
  "Hospitality": "🛎️",
  "Hotel": "🏨",
  "HR Services": "👥",
  "Import": "🛳️",
  "Industrial Machinery": "🏭",
  "Interior Design": "🛋️",
  "IT Services": "🌐",
  "Jewellery": "💍",
  "Kitchen Equipment": "🔪",
  "Leather": "👞",
  "Legal Services": "⚖️",
  "Logistics": "📦",
  "Machine Tools": "🔧",
  "Manufacturing": "🏭",
  "Marine": "⚓",
  "Marketing": "📈",
  "Media": "📰",
  "Medical Equipment": "🩺",
  "Mining": "⛏️",
  "Mobile Accessories": "🎧",
  "NGO": "🤝",
  "Packaging": "📦",
  "Paper": "📄",
  "Petroleum": "🛢️",
  "Pharmaceutical": "💊",
  "Photography": "📷",
  "Plastic": "🛍️",
  "Printing": "🖨️",
  "Real Estate": "🏢",
  "Recruitment": "📄",
  "Recycling": "♻️",
  "Renewable Energy": "☀️",
  "Research": "🔬",
  "Retail": "🏪",
  "Safety Equipment": "🦺",
  "Salon": "✂️",
  "Security Services": "👮",
  "Service Provider": "🤝",
  "Software": "💻",
  "Sports": "⚽",
  "Stationery": "✏️",
  "Steel": "🏗️",
  "Storage": "🗄️",
  "Supplier": "📦",
  "Telecommunications": "📡",
  "Textile": "🧵",
  "Tourism": "🗺️",
  "Trading": "💹",
  "Transportation": "🚛",
  "Travel": "✈️",
  "Warehouse": "🏭",
  "Waste Management": "🗑️",
  "Water Solutions": "💧",
  "Web Development": "🌐",
  "Wholesale": "📦",
  "Wood": "🪵",
  "Other": "✨",
  
  // Fallbacks
  "Food": "🍴",
  "Industrial": "🏭",
};