cat src/components/business/BusinessActionBar.tsx | grep -B 2 -A 5 "Share.share"
echo "--- BusinessDirectoryScreen ---"
cat src/screens/BusinessDirectoryScreen.tsx | grep -B 5 -A 2 "Share.share"
echo "--- SavedBusinessesScreen ---"
cat src/screens/SavedBusinessesScreen.tsx | grep -B 5 -A 2 "Share.share"
echo "--- BusinessCatalogScreen ---"
cat src/screens/BusinessCatalogScreen.tsx | grep -B 3 -A 2 "Share.share"
echo "--- MyAdvertisementsScreen ---"
cat src/screens/MyAdvertisementsScreen.tsx | grep -B 3 -A 2 "Share.share"
echo "--- AdvertisementDetailsScreen ---"
cat src/screens/AdvertisementDetailsScreen.tsx | grep -B 3 -A 2 "Share.share"
echo "--- MyRequirementsScreen ---"
cat src/screens/MyRequirementsScreen.tsx | grep -B 3 -A 2 "Share.share"
echo "--- LeadsScreen ---"
cat src/screens/LeadsScreen.tsx | grep -B 3 -A 2 "Share.share"
