import { supabase } from '../lib/supabase';
import { ArrowRight, Building2, Package, Users, Briefcase } from 'lucide-react';
import Link from 'next/link';

export default async function Home() {
  // Fetch a few featured businesses for internal linking
  const { data: businesses } = await supabase
    .from('businesses')
    .select('id, business_name, slug, profile_image, city, state')
    .order('created_at', { ascending: false })
    .limit(4);

  return (
    <div className="flex flex-col">
      {/* Hero Section */}
      <section className="bg-primary text-white py-20 px-6">
        <div className="max-w-4xl mx-auto text-center">
          <h1 className="text-4xl md:text-5xl font-extrabold mb-6 leading-tight">
            The Ultimate Hub for Our <span className="text-secondary">Community Ecosystem</span>
          </h1>
          <p className="text-lg md:text-xl opacity-90 mb-10 max-w-2xl mx-auto">
            Connect with verified businesses, explore high-quality products, discover new opportunities, and grow your network in a trusted environment.
          </p>
          <div className="flex flex-col sm:flex-row items-center justify-center gap-4">
            <a 
              href="https://play.google.com/store/apps/details?id=com.mandar.community"
              className="bg-secondary hover:bg-blue-600 text-white px-8 py-4 rounded-full font-bold text-lg shadow-lg flex items-center transition-all w-full sm:w-auto justify-center"
            >
              Download the App
            </a>
            <a 
              href="#explore"
              className="bg-white/10 hover:bg-white/20 text-white px-8 py-4 rounded-full font-bold text-lg border border-white/20 transition-all w-full sm:w-auto justify-center flex"
            >
              Explore Directory
            </a>
          </div>
        </div>
      </section>

      {/* Features Section */}
      <section className="py-16 px-6 bg-white">
        <div className="max-w-6xl mx-auto">
          <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-4 gap-8">
            <div className="p-6 bg-gray-50 rounded-2xl border border-gray-100 shadow-sm">
              <Building2 className="w-10 h-10 text-secondary mb-4" />
              <h3 className="text-xl font-bold mb-2 text-gray-900">Business Directory</h3>
              <p className="text-gray-600 text-sm">Find verified manufacturers, traders, and service providers from the community.</p>
            </div>
            <div className="p-6 bg-gray-50 rounded-2xl border border-gray-100 shadow-sm">
              <Package className="w-10 h-10 text-secondary mb-4" />
              <h3 className="text-xl font-bold mb-2 text-gray-900">Product Catalog</h3>
              <p className="text-gray-600 text-sm">Browse thousands of products directly from the sellers with transparent details.</p>
            </div>
            <div className="p-6 bg-gray-50 rounded-2xl border border-gray-100 shadow-sm">
              <Briefcase className="w-10 h-10 text-secondary mb-4" />
              <h3 className="text-xl font-bold mb-2 text-gray-900">B2B Leads</h3>
              <p className="text-gray-600 text-sm">Post requirements or fulfill active leads generated by fellow community members.</p>
            </div>
            <div className="p-6 bg-gray-50 rounded-2xl border border-gray-100 shadow-sm">
              <Users className="w-10 h-10 text-secondary mb-4" />
              <h3 className="text-xl font-bold mb-2 text-gray-900">Networking</h3>
              <p className="text-gray-600 text-sm">Expand your reach and grow your business with a tight-knit, trusted network.</p>
            </div>
          </div>
        </div>
      </section>

      {/* Featured Businesses */}
      <section id="explore" className="py-16 px-6 bg-gray-50">
        <div className="max-w-6xl mx-auto">
          <div className="flex justify-between items-end mb-10">
            <div>
              <h2 className="text-3xl font-bold text-gray-900 mb-2">Featured Businesses</h2>
              <p className="text-gray-600">Discover some of the top-rated enterprises in our network.</p>
            </div>
          </div>
          
          <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-6">
            {businesses?.map((biz) => (
              <Link href={`/biz/${biz.slug || biz.id}`} key={biz.id} className="bg-white rounded-2xl overflow-hidden shadow-sm border border-gray-100 hover:shadow-md transition-shadow group">
                <div className="h-32 bg-gray-200 relative">
                  {biz.profile_image && biz.profile_image.startsWith("http") ? (
                    <img src={biz.profile_image} alt={biz.business_name} className="w-full h-full object-cover" />
                  ) : (
                    <div className="w-full h-full bg-gradient-to-br from-primary to-secondary" />
                  )}
                </div>
                <div className="p-5 relative">
                  <h3 className="text-lg font-bold text-gray-900 mb-1 group-hover:text-secondary transition-colors line-clamp-1">{biz.business_name}</h3>
                  <p className="text-sm text-gray-500 line-clamp-1">{biz.city}{biz.state ? `, ${biz.state}` : ''}</p>
                </div>
              </Link>
            ))}
          </div>
          
          <div className="mt-10 text-center">
            <p className="text-gray-600 mb-4">Want to see all businesses or list your own?</p>
            <a href="https://play.google.com/store/apps/details?id=com.mandar.community" className="inline-flex items-center gap-2 text-secondary font-bold hover:underline">
              Download the App to access the full directory <ArrowRight className="w-4 h-4" />
            </a>
          </div>
        </div>
      </section>
    </div>
  );
}

